name: ecommerce_app_with_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # FIREBASE  
  firebase_core: ^3.10.1
  # CORE
  connectivity_plus: ^6.1.2
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
   # ANALYTICS
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
