// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5O-QAve-5KcCPqGWOO9d4MWJCUKE2kGc',
    appId: '1:96229027521:web:2c8765037b42f6a090ee40',
    messagingSenderId: '96229027521',
    projectId: 'ecom-1988f',
    authDomain: 'ecom-1988f.firebaseapp.com',
    storageBucket: 'ecom-1988f.firebasestorage.app',
    measurementId: 'G-PB8EXF9GSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANm-NJUd7zXcXuXRGW6uz8HNbhqf8u5SE',
    appId: '1:96229027521:android:1b74289a84db21a490ee40',
    messagingSenderId: '96229027521',
    projectId: 'ecom-1988f',
    storageBucket: 'ecom-1988f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0rJp5PmG5_S_KZnuUrTFCLYEXzwfoQW0',
    appId: '1:96229027521:ios:a034c4e2b86fb1ba90ee40',
    messagingSenderId: '96229027521',
    projectId: 'ecom-1988f',
    storageBucket: 'ecom-1988f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAppWithCleanArchitecture',
  );
}
